package io.github.retz.chopsticks;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kuenishi' at '9/7/16 1:51 PM' with Gradle 3.0
 *
 * @author kuenishi, @date 9/7/16 1:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
