package io.github.retz.chopsticks;

import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'kuenishi' at '9/7/16 1:51 PM' with Gradle 3.0
 *
 * @author kuenishi, @date 9/7/16 1:51 PM
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
